### ISSUE TITLE
text  dep version

### ISSUE THREAD

**Issue by ciez** [killerswan/Haskell-BLAKE#1]
Current text version is > 1.
can this dep:  text           >= 0 && < 1,

be changed to text >= 0?

**Comment by killerswan** [comment]
After Christmas, what I actually intend to do, @ciez, is pull this package off hackage, or mark it deprecated somehow.  I'm not sure anybody's using it in anger, and anyone who does is probably making a mistake: my code is likely too slow for good crypto.  :innocent:
